name: Fluxo de Trabalho de Pull Request para Python

on: [pull_request]

jobs:
  qa:
    name: Verificação de Qualidade
    runs-on: ubuntu-latest
    steps:
      - name: Fazer checkout do repositório
        uses: actions/checkout@v1
      
      - name: Configurar Python
        uses: actions/setup-python@master
        with:
          python-version: 3.12
      
      - name: Instalar Poetry e dependências
        run: |
          pip install -U pip
          pip install poetry==1.8.3
          poetry install
        env:
          POETRY_VIRTUALENVS_CREATE: false

      - name: Executar testes
        run: poetry run python manage.py test

      - name: Executar Wemake Python Styleguide
        uses: wemake-services/wemake-python-styleguide@0.16.0
        continue-on-error: true
        with:
          reporter: 'github-pr-review'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
