name: Python Pull Request Workflow

on:
  pull_request:

jobs:
  qa:
    name: Quality check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run Tests
        run: poetry run python manage.py test

      - name: Run Wemake Python Styleguide
        uses: wemake-services/wemake-python-styleguide@v0.16.0
        with:
          reporter: 'github-pr-review'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
