name: Python Pull Request Workflow

on:
  pull_request:
    branches:
      - '*'

jobs:
  qa:
    name: Quality check
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install poetry
        run: |
          pip install -U pip
          pip install poetry

      - name: Install dependencies
        run: poetry install
        env:
          POETRY_VIRTUALENVS_CREATE: false

      - name: Test
        run: poetry run python manage.py test

      - name: Run Wemake Python Styleguide
        uses: wemake-services/wemake-python-styleguide@0.16.0
        with:
          reporter: 'github-pr-review'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
